# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_OlaInterfaceDialog.ui'
#
# Created: Mon Jan 20 12:21:23 2014
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_OlaInterfaceDialog(object):
    def setupUi(self, OlaInterfaceDialog):
        OlaInterfaceDialog.setObjectName(_fromUtf8("OlaInterfaceDialog"))
        OlaInterfaceDialog.resize(480, 640)
        OlaInterfaceDialog.setModal(False)
        self.verticalLayout = QtGui.QVBoxLayout(OlaInterfaceDialog)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(OlaInterfaceDialog)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.wizard_tab = QtGui.QWidget()
        self.wizard_tab.setObjectName(_fromUtf8("wizard_tab"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.wizard_tab)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.wizard_tab)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 438, 534))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.stackedWidget = QtGui.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.getActivitiesPage = QtGui.QWidget()
        self.getActivitiesPage.setObjectName(_fromUtf8("getActivitiesPage"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.getActivitiesPage)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.webView = QtWebKit.QWebView(self.getActivitiesPage)
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("qrc:/plugins/olainterface/intro.html")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.verticalLayout_5.addWidget(self.webView)
        self.hostHorizontalLayout = QtGui.QHBoxLayout()
        self.hostHorizontalLayout.setObjectName(_fromUtf8("hostHorizontalLayout"))
        self.hostLabel = QtGui.QLabel(self.getActivitiesPage)
        self.hostLabel.setObjectName(_fromUtf8("hostLabel"))
        self.hostHorizontalLayout.addWidget(self.hostLabel)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.hostHorizontalLayout.addItem(spacerItem)
        self.hostLineEdit = QtGui.QLineEdit(self.getActivitiesPage)
        self.hostLineEdit.setMinimumSize(QtCore.QSize(220, 0))
        self.hostLineEdit.setInputMask(_fromUtf8(""))
        self.hostLineEdit.setText(_fromUtf8("http://www.landobservatory.org"))
        self.hostLineEdit.setObjectName(_fromUtf8("hostLineEdit"))
        self.hostHorizontalLayout.addWidget(self.hostLineEdit)
        self.verticalLayout_5.addLayout(self.hostHorizontalLayout)
        self.userHorizontalLayout = QtGui.QHBoxLayout()
        self.userHorizontalLayout.setObjectName(_fromUtf8("userHorizontalLayout"))
        self.userLabel = QtGui.QLabel(self.getActivitiesPage)
        self.userLabel.setObjectName(_fromUtf8("userLabel"))
        self.userHorizontalLayout.addWidget(self.userLabel)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.userHorizontalLayout.addItem(spacerItem1)
        self.userLineEdit = QtGui.QLineEdit(self.getActivitiesPage)
        self.userLineEdit.setMinimumSize(QtCore.QSize(220, 0))
        self.userLineEdit.setObjectName(_fromUtf8("userLineEdit"))
        self.userHorizontalLayout.addWidget(self.userLineEdit)
        self.verticalLayout_5.addLayout(self.userHorizontalLayout)
        self.passwordHorizontalLayout = QtGui.QHBoxLayout()
        self.passwordHorizontalLayout.setObjectName(_fromUtf8("passwordHorizontalLayout"))
        self.passwordLabel = QtGui.QLabel(self.getActivitiesPage)
        self.passwordLabel.setObjectName(_fromUtf8("passwordLabel"))
        self.passwordHorizontalLayout.addWidget(self.passwordLabel)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.passwordHorizontalLayout.addItem(spacerItem2)
        self.passwordLineEdit = QtGui.QLineEdit(self.getActivitiesPage)
        self.passwordLineEdit.setMinimumSize(QtCore.QSize(220, 0))
        self.passwordLineEdit.setEchoMode(QtGui.QLineEdit.Password)
        self.passwordLineEdit.setObjectName(_fromUtf8("passwordLineEdit"))
        self.passwordHorizontalLayout.addWidget(self.passwordLineEdit)
        self.verticalLayout_5.addLayout(self.passwordHorizontalLayout)
        self.getActivitiesButton = QtGui.QPushButton(self.getActivitiesPage)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/olainterface/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.getActivitiesButton.setIcon(icon)
        self.getActivitiesButton.setObjectName(_fromUtf8("getActivitiesButton"))
        self.verticalLayout_5.addWidget(self.getActivitiesButton)
        self.stackedWidget.addWidget(self.getActivitiesPage)
        self.startEditingPage = QtGui.QWidget()
        self.startEditingPage.setObjectName(_fromUtf8("startEditingPage"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.startEditingPage)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.textBrowser = QtGui.QTextBrowser(self.startEditingPage)
        self.textBrowser.setObjectName(_fromUtf8("textBrowser"))
        self.verticalLayout_6.addWidget(self.textBrowser)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.back1Button = QtGui.QPushButton(self.startEditingPage)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/olainterface/go-previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.back1Button.setIcon(icon1)
        self.back1Button.setObjectName(_fromUtf8("back1Button"))
        self.horizontalLayout_7.addWidget(self.back1Button)
        self.startEditingActivityButton = QtGui.QPushButton(self.startEditingPage)
        self.startEditingActivityButton.setEnabled(True)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/olainterface/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.startEditingActivityButton.setIcon(icon2)
        self.startEditingActivityButton.setObjectName(_fromUtf8("startEditingActivityButton"))
        self.horizontalLayout_7.addWidget(self.startEditingActivityButton)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        self.stackedWidget.addWidget(self.startEditingPage)
        self.editingTaggroupPage = QtGui.QWidget()
        self.editingTaggroupPage.setObjectName(_fromUtf8("editingTaggroupPage"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.editingTaggroupPage)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.submitActivityTextBrowser = QtGui.QTextBrowser(self.editingTaggroupPage)
        self.submitActivityTextBrowser.setObjectName(_fromUtf8("submitActivityTextBrowser"))
        self.verticalLayout_7.addWidget(self.submitActivityTextBrowser)
        self.taggroupTreeWidget = QtGui.QTreeWidget(self.editingTaggroupPage)
        self.taggroupTreeWidget.setObjectName(_fromUtf8("taggroupTreeWidget"))
        self.taggroupTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.verticalLayout_7.addWidget(self.taggroupTreeWidget)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.back2Button = QtGui.QPushButton(self.editingTaggroupPage)
        self.back2Button.setIcon(icon1)
        self.back2Button.setObjectName(_fromUtf8("back2Button"))
        self.horizontalLayout.addWidget(self.back2Button)
        self.submitActivityButton = QtGui.QPushButton(self.editingTaggroupPage)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/olainterface/open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.submitActivityButton.setIcon(icon3)
        self.submitActivityButton.setObjectName(_fromUtf8("submitActivityButton"))
        self.horizontalLayout.addWidget(self.submitActivityButton)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.stackedWidget.addWidget(self.editingTaggroupPage)
        self.verticalLayout_4.addWidget(self.stackedWidget)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.wizard_tab, _fromUtf8(""))
        self.log_tab = QtGui.QWidget()
        self.log_tab.setObjectName(_fromUtf8("log_tab"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.log_tab)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.loggingTextEdit = QtGui.QPlainTextEdit(self.log_tab)
        self.loggingTextEdit.setObjectName(_fromUtf8("loggingTextEdit"))
        self.verticalLayout_2.addWidget(self.loggingTextEdit)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.clearLogButton = QtGui.QPushButton(self.log_tab)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/olainterface/Edit-delete-2.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clearLogButton.setIcon(icon4)
        self.clearLogButton.setObjectName(_fromUtf8("clearLogButton"))
        self.horizontalLayout_3.addWidget(self.clearLogButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.tabWidget.addTab(self.log_tab, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.closeButton = QtGui.QPushButton(OlaInterfaceDialog)
        self.closeButton.setObjectName(_fromUtf8("closeButton"))
        self.horizontalLayout_2.addWidget(self.closeButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(OlaInterfaceDialog)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(OlaInterfaceDialog)

    def retranslateUi(self, OlaInterfaceDialog):
        OlaInterfaceDialog.setWindowTitle(QtGui.QApplication.translate("OlaInterfaceDialog", "Land Observatory Polygon Editor", None, QtGui.QApplication.UnicodeUTF8))
        self.hostLabel.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Host", None, QtGui.QApplication.UnicodeUTF8))
        self.userLabel.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.userLineEdit.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "admin", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLabel.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Password", None, QtGui.QApplication.UnicodeUTF8))
        self.passwordLineEdit.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "admin", None, QtGui.QApplication.UnicodeUTF8))
        self.getActivitiesButton.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Get Activities", None, QtGui.QApplication.UnicodeUTF8))
        self.textBrowser.setHtml(QtGui.QApplication.translate("OlaInterfaceDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<ul style=\"margin-top: 0px; margin-bottom: 0px; margin-left: 0px; margin-right: 0px; -qt-list-indent: 1;\"><li style=\" margin-top:12px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Select a deal on the map to get all detail information and start editing polygon geometries</li>\n"
"<li style=\" margin-top:0px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Go back to previous page to reload all activities for another extent</li></ul></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.back1Button.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.startEditingActivityButton.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Start editing Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.submitActivityTextBrowser.setHtml(QtGui.QApplication.translate("OlaInterfaceDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">All taggroups of the selected deal is shown in the tree below.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Edit or add the geometry of an existing taggroup using standard QGIS editing tools.</p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">After editing submit all changes with <span style=\" font-style:italic;\">Submit Activity</span>.</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.back2Button.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Back", None, QtGui.QApplication.UnicodeUTF8))
        self.submitActivityButton.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Submit Activity", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.wizard_tab), QtGui.QApplication.translate("OlaInterfaceDialog", "Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.clearLogButton.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Clear Log", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.log_tab), QtGui.QApplication.translate("OlaInterfaceDialog", "Log", None, QtGui.QApplication.UnicodeUTF8))
        self.closeButton.setText(QtGui.QApplication.translate("OlaInterfaceDialog", "Close", None, QtGui.QApplication.UnicodeUTF8))

from PyQt4 import QtWebKit
import resources_rc
